### ISSUE TITLE
vimrc support not documented

### ISSUE THREAD

**Issue by mloskot** [74th/vscode-vim#19]
There is no mention of support for `.vimrc`, `_vimrc` or a variation in the docs/README.

Scanning through the source code shows nothing related to use of the config files.
Is it considered, planned?

**Comment by 74th** [comment]
I don't plan to support `.vimrc`.
A goal of this extension is not to improve vim emulation, is to improve more friendly with vscode.
If you want settings of vim, please request them.

**Comment by mloskot** [comment]
I assume, you also mean there is no plan for custom config file, like vsvimrc in [VsVim](https://github.com/jaredpar/VsVim).
Yes, that's what I mean, setting e.g. custom mappings. I'll open a related request, thanks.

**Comment by mloskot** [comment]
Actually, I should keep it open as I think that caveat should be documented in the README.
