### ISSUE TITLE
Navigating with 'j' and 'k' doesn't scroll.

### ISSUE THREAD

**Issue by Plasticcaz** [74th/vscode-vim#2]
Just wanted to say, Thanks for doing this project.

However, one thing which is causing problems for me right now, is that using 'j' and 'k', for navigating up and down a text file doesn't scroll the displayed text, so when I navigate off screen, it still displays where I was already.

Obviously, it would be great if the displayed text would move as well when we press 'j' or 'k'.

**Comment by 74th** [comment]
Sorry, I could not find a way to scroll from extensions.
I added a issue in VSCode. https://github.com/Microsoft/vscode/issues/463
Please wait for updating VSCode and this plugin.

**Comment by 74th** [comment]
I fix and release. Please update this extension.
