### ISSUE TITLE
Add support for motion with jkl;

### ISSUE THREAD

**Issue by mloskot** [74th/vscode-vim#20]
(This is somewhat related to #19 issue.)

Many of Vim users prefer the *ergonomic* `jkl;` over the *historic* `hjkl`.

As there is no plan to support `.vimrc` of any kind, please add support for configuration setting to enable switching between those two mappings.

**Comment by 74th** [comment]
I support jkl; motions. Please update this plugin and add below to your settings.

```
"vimStyle.useErgonomicKeyForMotion": true,
```

**Comment by mloskot** [comment]
Awesome, works for me, thanks!
