### ISSUE TITLE
Search does not iterate through findings

### ISSUE THREAD

**Issue by msherwood21** [74th/vscode-vim#22]
After updating to the latest VS Code version with the latest release of vscode-vim, search acts like it can't find my text. It highlights them as I type, but will not iterate through what it finds.

![capture](https://cloud.githubusercontent.com/assets/5807030/11936537/300616b4-a7d4-11e5-973e-01fe8c8fa98b.PNG)

**Comment by 74th** [comment]
When the cursor is at a blank line, its may happened. But I don't find a reason.
Please begun to search without a blank line.

**Comment by 74th** [comment]
It may not be happened on current version.
