### ISSUE TITLE
Weird gray overlay extending along the cursor as you type

### ISSUE THREAD

**Issue by hyouuu** [74th/vscode-vim#23]
Hi - not sure if it's a feature or mistake, but I'm seeing this weird overlay after typing Esc for view mode then i for insert mode, then as I type along the gray overlay extend with my cursor, which makes the code looks really ugly...

<img width="713" alt="screen shot 2016-01-16 at 3 33 18 pm" src="https://cloud.githubusercontent.com/assets/5061867/12375072/ab4ef074-bc66-11e5-990f-9fc3baf2ab2f.png">

**Comment by 74th** [comment]
It may not be happened in current version. Sorry for waiting.
