### ISSUE TITLE
why highlight all the same letter 

### ISSUE THREAD

**Issue by DrakeLeung** [74th/vscode-vim#24]
When I move the cursor on the letter `e` in the *normal mode*, 
**all the rest of `e` are highlighted**.

![0](https://cloud.githubusercontent.com/assets/6823863/13137931/0c58bdac-d65f-11e5-94f8-7d00d2945a28.png)

Is it a feature or a bug? If former, can I turn it off in the settings?

**Comment by 74th** [comment]
This plugin uses selection to divide mode between normal and insert.
Please add this setting to your `settings.json`.

```
"editor.selectionHighlight": false,
```
