### ISSUE TITLE
Undo support

### ISSUE THREAD

**Issue by neptunian** [74th/vscode-vim#25]
Any reason why 'u' isn't supported for undo?

**Comment by 74th** [comment]
Undo does not behave exactly as vim undo.

**Comment by neptunian** [comment]
@74th I see, though it seems to work in this Vim plugin fine: https://github.com/VSCodeVim/Vim

**Comment by 74th** [comment]
This plugin will not support actios VSCode has. 
But I'll support user keybindings which call actions of VSCode and other plugins.

**Comment by MarcoPeraza** [comment]
74th, you have good reasons but please reconsider.  Undo is a fundamental operation that I do *all the time*.  The reason for using your plugin is that my hands know how to use vim.  "u" is as ingrained as hjkl, i, and ESC.  Given that I'm installing a vim plugin, I expect u to undo. Given that it's a plugin for vscode, I accept that vscode's undo might not be exactly like vim's undo, but I can deal with that and it's probably going to be the same behavior as Vim's undo for almost all cases.

**Comment by Wayt** [comment]
Totally agree with @MarcoPeraza, user keybindings would allow that, depend on everyone preferences.

Keep going, great work !

**Comment by 74th** [comment]
VSCode undo goes back until last typing enter key. Extentions can't treat it. This problem is not easy...
https://github.com/Microsoft/vscode/issues/4313

After to make user keybinding, I will try to make a subset of vim undo.

**Comment by 74th** [comment]
I was able to call VSCode command from `u` `:` `/` `n` `N` `>` `<`.
In this version, when yout type `u`, it call vscode undo command.
