### ISSUE TITLE
Extension stops working completely

### ISSUE THREAD

**Issue by drewcassidy** [74th/vscode-vim#3]
After only a few minutes of usage on Mac OS X the extension completely stopped working. no letter keys will work, though arrows still move the cursor. I would provide logs but I dont know where to find them

**Comment by 74th** [comment]
I'm sorry to trouble you.
I found a bug that press w at the line which has no characters ,and fix it now.
Please update this plugin and try to use it.

**Comment by drewcassidy** [comment]
Alright that appears to have fixed it
