### ISSUE TITLE
Option for keeping the block cursor in insert mode.

### ISSUE THREAD

**Issue by twanies** [74th/vscode-vim#31]
I am using a block cursor, but in insert mode it goes to a line cursor. Any idea how to fix this? Or is it just impossible in the current release?

**Comment by 74th** [comment]
OK. I'll add this option.

**Comment by twanies** [comment]
Btw. When pressing o or O currently their is currently no indentation.

**Comment by 74th** [comment]
I support this option. Please update this plugin.

**Comment by 74th** [comment]
Indentation bug may be fix with #38 .
