### ISSUE TITLE
Cursor blinks back and forth when holding down movement keys

### ISSUE THREAD

**Issue by SLAPaper** [74th/vscode-vim#32]
When holding the movement keys like `hjkl(;)w`, the cursor will blink between a former position and a newer position, which looks really strange and significantly disturbs editing. What's the problem? What additional information should I provide?
Thanks!

**Comment by 74th** [comment]
I see this problem, but I don't solve it yet.
Please tell me what platform do you use. Windows?

**Comment by SLAPaper** [comment]
Yes, I'm using Windows 10 Pro (Insider Preview Build 14342).
