### ISSUE TITLE
Incompatible with GuidLine

### ISSUE THREAD

**Issue by YXuewei** [74th/vscode-vim#36]
When using this with GuidLine installed. GuidLine will nor working.

**Comment by 74th** [comment]
What is GuidLine?

**Comment by YXuewei** [comment]
Sorry, my bad. I mean another extension called Guides. It provides you indentation lines. When I have both installed. The Guides is not working. Unistall VimStyle, indentation line got back. And checked with other vim emulator. Guides worked fine. So I guess it is VimStyle that doesn't work with Guides.

**Comment by 74th** [comment]
Thanks you for your report!
I found my extension breaks some options and fixed it.
Please update this plugin.
