### ISSUE TITLE
Text object operations not working

### ISSUE THREAD

**Issue by brycefricke** [74th/vscode-vim#37]
Example:
"This is text"
with cursor at 'T', execute di"

Expected result:
""

Actual result:
"This is text"

Running VS Code 1.2 on Win7.
vimStyle 0.3.9

Only thing unique about my settings.json is configuring a proxy.

**Comment by 74th** [comment]
Current version does not support text object command.
https://github.com/74th/vscode-vim/blob/master/quickref.md

**Comment by brycefricke** [comment]
Oh, sorry.  I guess I misread the quickref.  I saw the commands listed, but didn't notice the lack of VimStyle classes.  My bad.

**Comment by 74th** [comment]
New version 0.5.0 supports di" .
