### ISSUE TITLE
word motion bugs ( w e b ge gw dw cw ... )

### ISSUE THREAD

**Issue by 74th** [74th/vscode-vim#38]
There may be some bugs I cannot found. Please report bugs!! Word motion has many function!

```
aaa bbb ccc
^ dw

except:
bbb ccc

actual:
ccc
```

**Comment by 74th** [comment]
when cursor move over 3 blank line by `w`, it skips 1 line.

**Comment by 74th** [comment]
```
aaa ddd cccccc
        ^ dw

except:
aaa ddd 
       ^

actual:
aaa ddd c
        ^
```

**Comment by 74th** [comment]
```
aaa(LF)
^ dw
bbb

except:
(LF)
bbb

actual: delete LF
bbb
```

**Comment by jskulski** [comment]
On 0.3.9 this is current behavior for db

```
aaa bbb
      ^db 
aaa
```

It deletes forward like dw.

**Comment by 74th** [comment]
@jskulski Thank for your report. I'll try to fix them.

**Comment by jskulski** [comment]
@74th Thank you for vimstyle! It was the plugin that finally allowed me to use vscode (too addicted to vim keys).

**Comment by vogler** [comment]
1. `e` after `b` is broken, e.g., `be` goes to the end of the next word instead of the current word.
2. `b` and `e` don't work in visual mode

**Comment by 74th** [comment]
@vogler  Thank you for a report. I could find a bug when a cursor in a first character of a word and visual mode was not tested well. I try to fix them.

**Comment by vogler** [comment]
1.  is fixed, but visual mode is still buggy: `vb` works, `ve` and `vwb` don't.

**Comment by 74th** [comment]
`cw` at a last word of line leave the last charactor.

**Comment by tobia** [comment]
^^ or sometimes chomps the following line:

    Hello
    world!

pressing `cw` on the `H` leaves only the `!`

**Comment by bodqhrohro** [comment]
`ce` and `de` leave  the last character of the word instead of removing the whole word.
