### ISSUE TITLE
`ce` includes next word (excluding its last character)

### ISSUE THREAD

**Issue by nvanmeurs** [74th/vscode-vim#39]
Example line:
`This sentenze has a typo.`

This can be reproduced using the following steps:
1. Move your cursor to the word `sentenze`
2. Type `ce`.

Actual result:
`This ss a typo.`

Expected result:
`This s has a typo.`

**Comment by 74th** [comment]
Thank you for your report.
VimStyle has a wrong `ce` function.
I test this action with `vim -u NONE`, but vim does not show your expected result.

```
This setenze has a typo.
     ^ ce[ESC]

vim -u NONE show:
This  has a type.
    ^
```

I have not used `ce`, it seems same as `cw`.

* VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec  9 2014 17:36:41)

**Comment by nvanmeurs** [comment]
Yeah, in Vim it works as expected it replaces up to the end of the word.
I got the `ce` command from the vimtutorial as I started to learn Vim yesterday.
I'm very happy with your VSCode plugin. Will use `cw` for now, since that one does work properly?
