### ISSUE TITLE
I can't input +

### ISSUE THREAD

**Issue by nati** [74th/vscode-vim#4]
Thank you for your writing nice extension!

I can't input + in insert mode.

If I input +, it turns out to * on each two times input just like 
*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*

vsCode: Version 0.10.2 (0.10.2)  7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066
OS: Mac OSX Yosemite
Keyboard: US

**Comment by drewcassidy** [comment]
I just made a pull request to fix that
