### ISSUE TITLE
number accelerators don't round down

### ISSUE THREAD

**Issue by otacon507** [74th/vscode-vim#40]
There is one small issue I have found so far:

When I am on line 6, and the file totals only 15 lines, if I do:`20j` then it should still round 20 down to 15 and subsequently go to line 15. Currently, you must give it an exact number, `9j` in this case, to reach down to line 15.

**Comment by 74th** [comment]
Thank you for a report. I'll fix it for a next version. For your case, my plugin supports `G`.
