### ISSUE TITLE
no vim mode enable option in settings.json or shortcut to toggle this mode ?

### ISSUE THREAD

**Issue by daizhan** [74th/vscode-vim#41]

**Comment by 74th** [comment]
This plugin does not have no vim mode.
What case do you need?
I think it is not difficult to add the shortcut.

**Comment by daizhan** [comment]
@74th  I means there is no way back to original vscode edit mode once I installed the vim plugin. 
sometimes a shortcut or switch is a friendly option to user, like sublime text.

**Comment by 74th** [comment]
@daizhan Can you use that default mode option sets insert? Do you need another switch?

```
// default mode (default: "normal")
"vimStyle.defaultMode": "insert",
```

**Comment by daizhan** [comment]
@74th  OK, maybe my description is not clear enough.  I need another switch that can diable or enable vim feature.  for example `vimStyle.enable: true` or a shortcut
I think that can improve experience. user don't have to uninstall the plugin to back original. after all the vim feature is not completely compatible and vscode also has its own feature.

**Comment by 74th** [comment]
This option is supported now.

```
// disable without to uninstall (default: "true")
"vimStyle.enabled": "false",
```

**Comment by daizhan** [comment]
Great,  thank you very much.

**Comment by daizhan** [comment]
I find another enhafincement that make a shortcuts  to the option `vimStyle.enabled`, like `vim.Esc`.

do you have any idea to workaround it ?

**Comment by 74th** [comment]
Sorry, waiting for next update. #45
