### ISSUE TITLE
Allow jj for Esc

### ISSUE THREAD

**Issue by mloskot** [74th/vscode-vim#42]
This question is related to [support for motion with jkl;](https://github.com/74th/vscode-vim/issues/20),

I'd like to map `jj` (double `j`) for `Esc` and I'm trying this `keybindings.json` setting, but without any success:

```
{
    "key": "jj",
    "command": "vim.Esc",
    "when": "editorTextFocus"
}
```

Is `jj` be feasible?

**Comment by 74th** [comment]
When use this extension, a keybinding without additional keys do not work.
But I hear same request. I'll try to support it.

**Comment by 74th** [comment]
This option is supported now. Please try it.

```
// keys go to normal mode from insert mode (default: "" disable)
"vimStyle.imapEsc": "jj"
```

**Comment by mloskot** [comment]
This is great, works like charm. Thank you so much!

**Comment by seyhaheng2** [comment]
where to puts the code?

**Comment by 74th** [comment]
@seyhaheng2
Please add to the user settings(F1->open user settings).

**Comment by seyhaheng2** [comment]
@74th thank you

**Comment by exhuma** [comment]
For the google-nauts: This no longer works. The working solution (as of 2020) can [be found on StackOverflow](https://stackoverflow.com/a/38604086/160665).
