### ISSUE TITLE
Motion commands in visual mode

### ISSUE THREAD

**Issue by tobia** [74th/vscode-vim#44]
There are a few motion commands that do not seem to work in visual mode:
- arrow keys
- most word motions (e E w W b B …) only w and B seem to work
- others?

The arrow keys make the visual selection disappear, but the status bar still says VISUAL and pressing any Vim motion key restores it.

**Comment by dylandjian** [comment]
hi, any update on this bug ?

**Comment by 74th** [comment]
@dylandjian  Almost motions were fixed. But it doesn't support arrow keys.

**Comment by 74th** [comment]
arrow keys -> #57
