### ISSUE TITLE
input chinese in vim mode,then press shift,the character beside cursor was be covered!

### ISSUE THREAD

**Issue by cuitl** [74th/vscode-vim#49]
when the editor in vim mode ,I input Chinese,but I don't want it,then I press 'shift'. 
I expected this operation to avoid typing text,but it failed,it replace the charactors besides the cursor position. And if I user vim or amVim it won't have this problem.

**Comment by Arnie97** [comment]
Confirmed on Linux with fcitx-sogoupinyin, but have no idea how to fix it.
