### ISSUE TITLE
Add support for CI and VI

### ISSUE THREAD

**Issue by sethstha** [74th/vscode-vim#59]
This is exactly what I was looking for. Similar to sublime vim mode.

We just need Change Inner(ci) and Visually select Inner (vi)

Thanks for your great work.

**Comment by 74th** [comment]
New version 0.5.0 supports ci' ci( .

**Comment by sethstha** [comment]
Wow, just got the update. This saved my life.

Thanks, Now i can switch from Sublime Text.

**Comment by 74th** [comment]
but not supprt vi( , ciw yet
