### ISSUE TITLE
Multi-cursor Support

### ISSUE THREAD

**Issue by sethstha** [74th/vscode-vim#64]
This is the best vim emulator for VSCode. Similar to sublime text that I am used to. But the only thing that is drowning me is a lack of support for multicursor.

Do you have any intention of supporting it?

Thanks for the great plugin, still saving a lot of time.

**Comment by 74th** [comment]
With this extension, I'm not planning to provide more functionality than Vim.

**Comment by danab** [comment]
Currently if I attempt to use multiple cursors (out of habit) it completely breaks and I can't re-enter normal mode. It seems if you aren't going to support multiple cursors it should at least fail a bit more gracefully.

To recreate:

- Highlight word ( `vw` )
- Select Multiple Words ( `Cmd+D` )
- Change word (`c`)
- Try to get back to normal mode (`Esc`) and receive error "Running the contributed command:'vim.Esc' failed." Forced to restart

**Comment by rvlewerissa** [comment]
@danab Same issue as mine: #69 
Not only that, when I go to visual mode then press `c`, it does the same.

**Comment by 74th** [comment]
@danab Thank you for your information. I fixed it. Please update this plugin.
