### ISSUE TITLE
when it clicks with no selected text, it keeps VISUAL mode

### ISSUE THREAD

**Issue by kkorus** [74th/vscode-vim#65]
**Steps to reproduce:**

1. Select some text (with mouse) in "VISUAL" mode.
2. Place cursor somewhere in the code and click with left mouse.
3. Press "i", it keeps being in "VISUAL" mode instead of "INSERT".

To "fix" it I need to press "ESC" and then "i" again to have "INSERT" mode.

**Comment by kkorus** [comment]
@74th thanks for develiring support for `J` :) do you know when we can expect this bug fix? Cheers.

**Comment by 74th** [comment]
@kkorus Sorry, not yet.

**Comment by kkorus** [comment]
@74th Could you was able to reproduce it? To be honest it's quite annoying :(

**Comment by 74th** [comment]
@kkorus This is a bug issue, and I think it will change to normal mode with single click. So it is abe to change to insert when i key is pressed. 
Do you think it has to keep visual mode?

**Comment by kkorus** [comment]
@74th If just do simply single slick and press `i` it goes to insert -that's ok, but when select more text and do single slick and then press `i` it keeps visual mode - that's not ok.

**Comment by 74th** [comment]
I released v0.5.2, it seems good for this bug.

**Comment by kkorus** [comment]
@74th I will have a look, thanks 😉
