### ISSUE TITLE
Running the contributed command: 'vim.Esc' failed

### ISSUE THREAD

**Issue by rvlewerissa** [74th/vscode-vim#69]
<img width="1440" alt="screen shot 2017-12-11 at 3 22 38 pm" src="https://user-images.githubusercontent.com/15160023/33821731-914ca58c-de87-11e7-8696-665586104827.png">

Any ideas why? I had to restart every time this occurs.

Thanks!

**Comment by 74th** [comment]
I have not seen it recently.
Please let me know the situation that occurred in detail.

**Comment by rvlewerissa** [comment]
@74th Hmmm, okay. I'll put on the detail when this occurs again.

**Comment by rvlewerissa** [comment]
Ok I think I now how to reproduce it:

1. Start with normal mode.
2. Multi select a word using your `Add Selection To Next Find Match` binding.
3. Press `c`.
4. Go back to normal mode.

**Comment by 74th** [comment]
@rvlewerissa Thank you for your information. I fixed it. Please update this plugin.
