### ISSUE TITLE
easymotion tags look weird

### ISSUE THREAD

**Issue by QuinnFreedman** [74th/vscode-vim#78]
By default, the easymotion markers look pretty funky (see screenshot below).

![screen shot 2018-08-05 at 5 46 06 pm](https://user-images.githubusercontent.com/10150390/43691911-9d498b24-98d7-11e8-820d-a0c875beac4e.png)

I know that you can style them to some extent with:

`vim.easymotionMarkerBackgroundColor`,
`vim.easymotionMarkerForegroundColorOneChar`,
`vim.easymotionMarkerForegroundColorTwoChar`,
`vim.easymotionMarkerWidthPerChar`,
`vim.easymotionMarkerHeight`,
`vim.easymotionMarkerFontFamily`,
`vim.easymotionMarkerFontSize`,
`vim.easymotionMarkerFontWeight`,
`vim.easymotionMarkerYOffset`.

However, no matter what I do, I can't get it to look like they are normal characters in the document because of the offsets of the text within the markers and the x-offset of the marker relative to the letters in the actual document.

Also, half of them are italic for some reason? I'm not really sure what that means.

What I think would be really helpful is either:
* An option to provide arbitrary CSS for the tags so users can style them however they want (e.g. padding, margins, line-height)
* Or, an option to display them in-line with the text so it just looks like the actual text of the document is changing when you go into jump mode, the way it is in Vim

**Comment by 74th** [comment]
You may use other vim extension.
VimStyle has no easymotion features.

**Comment by QuinnFreedman** [comment]
If I didn't want easy motion, I could also just disable it with `"vim.easymotion": false`. My point is that I want to use it but I want it to be legible
