### ISSUE TITLE
A collective thankyou from the internet. 

### ISSUE THREAD

**Issue by ichpuchtli** [74th/vscode-vim#8]
![image](https://cloud.githubusercontent.com/assets/1134912/11415830/a57bb08c-9453-11e5-8184-6513fab9b621.png)

**Comment by CPonty** [comment]
Thank ༼ つ ◕_◕ ༽つ

**Comment by misaxi** [comment]
thanks thanks thanks

**Comment by 74th** [comment]
♪〜

**Comment by jeffschwartz** [comment]
It is a wonderful and very much appreciated start. Domo arigatou gozaimasu :)

**Comment by mpseidel** [comment]
Thanks! :)

**Comment by twanies** [comment]
Thanks dude! I can't wait for the 'r' command.

**Comment by 74th** [comment]
@twanies Sorry, I kept you waiting. This supports 'r' now.

**Comment by tsirolnik** [comment]
yes, very thanks

**Comment by johnwook** [comment]
👍  Thank you!
