### ISSUE TITLE
No handler found for the command: 'vim.j'

### ISSUE THREAD

**Issue by jrife** [74th/vscode-vim#9]
After installing this plugin and restarting visual studio code I get a warning like
"No handler found for the command: 'vim.j'"
pop up for every key I press inside the editor. Attached is my version information and what I see in the editor with the plugin installed

![screenshot from 2015-11-26 12 26 33](https://cloud.githubusercontent.com/assets/2738417/11429113/f639112e-9438-11e5-8112-675b72e2dd60.png)
![screenshot from 2015-11-26 12 28 04](https://cloud.githubusercontent.com/assets/2738417/11429123/2d1ed6c4-9439-11e5-9bf7-08a18baa00fc.png)

Not sure if I'm just missing something or if this is a bug.

**Comment by DrakeLeung** [comment]
:+1:  in Ubuntu 14.04

**Comment by 74th** [comment]
I'll try to test in Ubuntu this weekend.

**Comment by 74th** [comment]
fix at 7ad6b19b7d09d2ac4867c4a9281c0632485f5818 .
Please reinstall this plugin and try it.

**Comment by jrife** [comment]
It now seems to work for me. Thank you :+1:
